<a href="https://colab.research.google.com/github/Jyothsna-20PH0528/C/blob/main/machinelearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# prompt: 1.	Compute Central Tendency Measures: Mean, Median, Mode Measure of Dispersion: Variance, Standard Deviation.

import numpy as np

# Sample data (replace with your actual data)
data = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

# Calculate mean
mean = np.mean(data)
print(f"Mean: {mean}")

# Calculate median
median = np.median(data)
print(f"Median: {median}")

# Calculate mode
from scipy import stats
mode = stats.mode(data)
print(f"Mode: {mode.mode}")


# Calculate variance
variance = np.var(data)
print(f"Variance: {variance}")

# Calculate standard deviation
std_dev = np.std(data)
print(f"Standard Deviation: {std_dev}")


Mean: 5.0
Median: 5.0
Mode: 5
Variance: 6.0
Standard Deviation: 2.449489742783178


In [4]:
# prompt: Apply the following Pre-processing techniques for a given dataset.
# a. Attribute selection
# b. Handling Missing Values
# c. Discretization
# d. Elimination of Outliers

import numpy as np
from scipy import stats
import pandas as pd

# Sample data (replace with your actual data)
data = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 100] #added an outlier


# Convert the data to a pandas DataFrame for easier manipulation.
df = pd.DataFrame({'value': data})

# a. Attribute Selection (Assuming 'value' is the only attribute)
#  In this simple example, we only have one attribute, so selection isn't necessary.
#  For multiple attributes, you'd use feature importance from models or correlation analysis


# b. Handling Missing Values (if any)
# Check for missing values
print("Missing Values:", df.isnull().sum())
# If there were missing values, you could replace them using imputation techniques like:
# df['value'].fillna(df['value'].mean(), inplace=True) # Mean imputation
# df['value'].fillna(df['value'].median(), inplace=True) # Median imputation
# or more advanced methods like k-NN imputation.



# c. Discretization
# Equal-width binning
num_bins = 3
df['discretized_value'] = pd.cut(df['value'], bins=num_bins, labels=False) #labels=False provides integer labels
print(f"\nDiscretized Values (Equal Width):\n{df}")

# d. Elimination of Outliers (using z-score method)
z = np.abs(stats.zscore(df['value']))
threshold = 2 #z-score threshold
df_no_outliers = df[(z < threshold)]
print(f"\nDataframe without Outliers:\n{df_no_outliers}")


# Calculate mean, median, mode, variance, and standard deviation
print(f"\nMean: {np.mean(df_no_outliers['value'])}")
print(f"Median: {np.median(df_no_outliers['value'])}")
print(f"Mode: {stats.mode(df_no_outliers['value']).mode}")
print(f"Variance: {np.var(df_no_outliers['value'])}")
print(f"Standard Deviation: {np.std(df_no_outliers['value'])}")



Missing Values: value    0
dtype: int64

Discretized Values (Equal Width):
    value  discretized_value
0       1                  0
1       2                  0
2       3                  0
3       4                  0
4       5                  0
5       5                  0
6       6                  0
7       7                  0
8       8                  0
9       9                  0
10    100                  2

Dataframe without Outliers:
   value  discretized_value
0      1                  0
1      2                  0
2      3                  0
3      4                  0
4      5                  0
5      5                  0
6      6                  0
7      7                  0
8      8                  0
9      9                  0

Mean: 5.0
Median: 5.0
Mode: 5
Variance: 6.0
Standard Deviation: 2.449489742783178


In [5]:
# prompt: Apply KNN algorithm for classification and regression

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import classification_report, mean_squared_error

# Sample classification data (replace with your actual data)
data = {'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'feature2': [2, 4, 1, 3, 5, 6, 8, 7, 9, 10],
        'target': [0, 0, 1, 1, 0, 1, 1, 0, 1, 1]}
df_classification = pd.DataFrame(data)

# Sample regression data (replace with your actual data)
data = {'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'feature2': [2, 4, 1, 3, 5, 6, 8, 7, 9, 10],
        'target': [5, 10, 8, 12, 15, 18, 20, 22, 25, 30]}
df_regression = pd.DataFrame(data)

# Classification
X_class = df_classification[['feature1', 'feature2']]
y_class = df_classification['target']
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(X_class, y_class, test_size=0.2, random_state=42)
knn_classifier = KNeighborsClassifier(n_neighbors=3) # You can adjust n_neighbors
knn_classifier.fit(X_train_class, y_train_class)
y_pred_class = knn_classifier.predict(X_test_class)
print("Classification Report:\n", classification_report(y_test_class, y_pred_class))


# Regression
X_reg = df_regression[['feature1', 'feature2']]
y_reg = df_regression['target']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
knn_regressor = KNeighborsRegressor(n_neighbors=3) # You can adjust n_neighbors
knn_regressor.fit(X_train_reg, y_train_reg)
y_pred_reg = knn_regressor.predict(X_test_reg)
print(f"\nRegression Mean Squared Error: {mean_squared_error(y_test_reg, y_pred_reg)}")


Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      1.00      0.67         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2


Regression Mean Squared Error: 1.888888888888888


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values

dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, [1, 2, 3]].values
y = dataset.iloc[:, -1].values
print(len(X))
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

FileNotFoundError: [Errno 2] No such file or directory: 'Social_Network_Ads.csv'

In [12]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data  # Features
y = iris.target  # Target variable (classes)

# Split the dataset into a training set and a testing set (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# You can experiment with different values of K to find the optimal one through cross-validation.
from sklearn.metrics import pairwise_distances

# For simplicity, we'll use Euclidean distance as the distance metric
distances = pairwise_distances(X_test, X_train, metric='euclidean')
import numpy as np

def find_k_nearest_neighbors(distances, k):
    # Find the indices of the K-nearest neighbors for each test sample
    k_nearest_neighbors_indices = np.argsort(distances, axis=1)[:, :k]
    return k_nearest_neighbors_indices

k = 5  # Choose the value of K
k_nearest_neighbors_indices = find_k_nearest_neighbors(distances, k)

from scipy.stats import mode

def predict_majority_class(k_nearest_neighbors_indices, y_train):
    # Get the classes of the K-nearest neighbors
    k_nearest_classes = y_train[k_nearest_neighbors_indices]

    # Predict the class based on the majority class among the neighbors
    predictions, _ = mode(k_nearest_classes, axis=1)
    return predictions.ravel()

y_pred = predict_majority_class(k_nearest_neighbors_indices, y_train)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))



Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [13]:
# prompt: knn with regression

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

# Sample regression data (replace with your actual data)
data = {'feature1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'feature2': [2, 4, 1, 3, 5, 6, 8, 7, 9, 10],
        'target': [5, 10, 8, 12, 15, 18, 20, 22, 25, 30]}
df_regression = pd.DataFrame(data)

# Regression
X_reg = df_regression[['feature1', 'feature2']]
y_reg = df_regression['target']
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
knn_regressor = KNeighborsRegressor(n_neighbors=3) # You can adjust n_neighbors
knn_regressor.fit(X_train_reg, y_train_reg)
y_pred_reg = knn_regressor.predict(X_test_reg)
print(f"\nRegression Mean Squared Error: {mean_squared_error(y_test_reg, y_pred_reg)}")



Regression Mean Squared Error: 1.888888888888888


In [14]:
# prompt: knn with classification

# Assuming 'X' and 'y' are your features and target variable, respectively.
# You've already loaded and preprocessed your data.

# Assuming X_train, X_test, y_train, y_test are defined from previous code
# Example using the loaded dataset
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [15]:
# prompt: 4.	Demonstrate decision tree algorithm for a classification problem and perform parameter tuning for better results

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load your data (replace with your actual data loading)
# Assuming X_train, X_test, y_train, y_test are already defined

# Initialize the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Define the parameter grid for tuning
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Perform GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=dt_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best parameters and best estimator
best_params = grid_search.best_params_
best_dt_classifier = grid_search.best_estimator_

print(f"Best parameters: {best_params}")

# Make predictions on the test set using the best model
y_pred = best_dt_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Best parameters: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10}
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [16]:
# prompt: decision tree for classification

# Assuming X_train, X_test, y_train, y_test are defined from previous code
# Initialize the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Train the classifier
dt_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = dt_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [18]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
# Read dataset
df_net = pd.read_csv('/content/Social_Network_Ads.csv')
df_net.head()
# Get required data
df_net.drop(columns = ['User ID'], inplace=True)
df_net.head()
# Describe data
df_net.describe()
# Salary distribution
sns.distplot(df_net['EstimatedSalary'])
# Label encoding
le = LabelEncoder()
df_net['Gender']= le.fit_transform(df_net['Gender'])
# Correlation matrix
df_net.corr()
sns.heatmap(df_net.corr())
# Split data into dependent/independent variables
X = df_net.iloc[:, :-1].values
y = df_net.iloc[:, -1].values
# Split data into test/train set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = True)
# Scale dataset
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# Decision Tree Classification
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
# Prediction
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))
# Accuracy
accuracy_score(y_test, y_pred)
# Classification report
print(f'Classification Report: \n{classification_report(y_test, y_pred)}')

FileNotFoundError: [Errno 2] No such file or directory: '/content/Social_Network_Ads.csv'

In [20]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']
# load dataset
pima = pd.read_csv("diabetes.csv", header=None, names=col_names)
pima.head()
#split dataset in features and target variable
feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Features
y = pima.label # Target variable
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))



FileNotFoundError: [Errno 2] No such file or directory: 'diabetes.csv'

In [21]:
# prompt: decision tree algorithm for a regression problem

from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Assuming your data is in a pandas DataFrame called 'df_regression'
# with features in columns 'feature1', 'feature2', etc., and target variable 'target'

# Separate features (X) and target (y)
X = df_regression.drop('target', axis=1)
y = df_regression['target']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Decision Tree Regressor
dt_regressor = DecisionTreeRegressor(random_state=42)

# Train the model
dt_regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = dt_regressor.predict(X_test)

# Evaluate the model using Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


Mean Squared Error: 6.5


In [22]:
# Importing the libraries
import numpy as np # for array operations
import pandas as pd # for working with DataFrames
import requests, io # for HTTP requests and I/O commands
import matplotlib.pyplot as plt # for data visualization
%matplotlib inline

# scikit-learn modules
from sklearn.model_selection import train_test_split # for splitting the data
from sklearn.metrics import mean_squared_error # for calculating the cost function
from sklearn.tree import DecisionTreeRegressor # for building the model

# Importing the dataset from the url of the data set
url = "https://drive.google.com/u/0/uc?id=1mVmGNx6cbfvRHC_DvF12ZL3wGLSHD9f_&export=download"
data = requests.get(url).content

# Reading the data
dataset = pd.read_csv(io.StringIO(data.decode('utf-8')))
dataset.head()

x = dataset.drop('Petrol_Consumption', axis = 1) # Features
y = dataset['Petrol_Consumption']  # Target

# Splitting the dataset into training and testing set (80/20)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 28)

# Initializing the Decision Tree Regression model
model = DecisionTreeRegressor(random_state = 0)

# Fitting the Decision Tree Regression model to the data
model.fit(x_train, y_train)

# Predicting the target values of the test set
y_pred = model.predict(x_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)),'.3f'))
print("\nRMSE:",rmse)

# Visualizing the decision tree structure
from sklearn.tree import export_graphviz

# export the decision tree model to a tree_structure.dot file
# paste the contents of the file to webgraphviz.com
export_graphviz(model, out_file ='tree_structure.dot',
               feature_names = ['Petrol_tax', 'Average_income', 'Paved_Highways', 'Population_Driver_licence(%)'])


RMSE: 133.351


In [23]:
# prompt: Random Forest algorithm for classification and regression

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# ... (Your existing code) ...

# Classification using Random Forest
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42) # You can adjust n_estimators
rf_classifier.fit(X_train, y_train)
y_pred_rf_class = rf_classifier.predict(X_test)
print("Random Forest Classification Report:\n", classification_report(y_test, y_pred_rf_class))


# Regression using Random Forest
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42) # You can adjust n_estimators
rf_regressor.fit(X_train_reg, y_train_reg)
y_pred_rf_reg = rf_regressor.predict(X_test_reg)
print(f"\nRandom Forest Regression Mean Squared Error: {mean_squared_error(y_test_reg, y_pred_rf_reg)}")


ValueError: Found input variables with inconsistent numbers of samples: [8, 38]

In [25]:
# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz
bank_data['default'] = bank_data['default'].map({'no':0,'yes':1,'unknown':0})
bank_data['y'] = bank_data['y'].map({'no':0,'yes':1})

NameError: name 'bank_data' is not defined

In [26]:
# Importing the libraries
import numpy as np # for array operations
import pandas as pd # for working with DataFrames
import requests, io # for HTTP requests and I/O commands
import matplotlib.pyplot as plt # for data visualization
%matplotlib inline

# scikit-learn modules
from sklearn.model_selection import train_test_split # for splitting the data
from sklearn.metrics import mean_squared_error # for calculating the cost function
from sklearn.ensemble import RandomForestRegressor # for building the model

# Importing the dataset from the url of the data set
url = "https://drive.google.com/u/0/uc?id=1mVmGNx6cbfvRHC_DvF12ZL3wGLSHD9f_&export=download"
data = requests.get(url).content

# Reading the data
dataset = pd.read_csv(io.StringIO(data.decode('utf-8')))
dataset.head()

x = dataset.drop('Petrol_Consumption', axis = 1) # Features
y = dataset['Petrol_Consumption']  # Target

# Splitting the dataset into training and testing set (80/20)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 28)

# Initializing the Random Forest Regression model with 10 decision trees
model = RandomForestRegressor(n_estimators = 10, random_state = 0)

# Fitting the Random Forest Regression model to the data
model.fit(x_train, y_train)

# Predicting the target values of the test set
y_pred = model.predict(x_test)

# RMSE (Root Mean Square Error)
rmse = float(format(np.sqrt(mean_squared_error(y_test, y_pred)),'.3f'))
print("\nRMSE:\n",rmse)


RMSE:
 96.389


In [27]:
# prompt: Naïve Bayes Classification algorithm

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Load your dataset (replace 'your_data.csv' with your actual file)
try:
  df = pd.read_csv('your_data.csv')
except FileNotFoundError:
  print("Error: 'your_data.csv' not found. Please upload your dataset.")
  df = pd.DataFrame() # Create an empty DataFrame to avoid further errors

if not df.empty:
  # Assuming 'target_column' is the name of your target variable column
  # and other columns are your features
  X = df.drop('target_column', axis=1)  # Features
  y = df['target_column']  # Target variable

  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Initialize the Gaussian Naive Bayes classifier
  gnb = GaussianNB()

  # Train the classifier
  gnb.fit(X_train, y_train)

  # Make predictions on the test set
  y_pred = gnb.predict(X_test)

  # Evaluate the model
  accuracy = accuracy_score(y_test, y_pred)
  print(f"Accuracy: {accuracy}")
  print("\nClassification Report:\n", classification_report(y_test, y_pred))
  print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Error: 'your_data.csv' not found. Please upload your dataset.


In [28]:
# prompt: Support Vector algorithm for classification

from sklearn.svm import SVC

# Assuming X_train, X_test, y_train, y_test are defined from previous code

# Initialize the Support Vector Classifier
svm_classifier = SVC(kernel='linear', C=1.0, random_state=42)  # You can adjust kernel and C

# Train the classifier
svm_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = svm_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


ValueError: Found input variables with inconsistent numbers of samples: [8, 38]

In [29]:
# prompt: simple linear regression algorithm for a regression problem

import numpy as np

def simple_linear_regression(X, y):
  """
  Performs simple linear regression.

  Args:
    X: A 1D numpy array of independent variable values.
    y: A 1D numpy array of dependent variable values.

  Returns:
    A tuple containing the slope (m) and y-intercept (b) of the regression line.
  """
  n = len(X)
  x_mean = np.mean(X)
  y_mean = np.mean(y)

  numerator = np.sum((X - x_mean) * (y - y_mean))
  denominator = np.sum((X - x_mean)**2)

  m = numerator / denominator
  b = y_mean - (m * x_mean)

  return m, b
